export const Data: any = (params: any) => {
  const dataTemplate = {
    ACTION: `ACTION = '${params}'`,
    ACTIONGROUP: `ACTION = '${params}'`,
    // AssetAttribute: `assetattrid in (select assetattrid from maximo.classspec where classstructureid in ('7955'))`,
    AUTOSCRIPT: `AUTOSCRIPT = '${params}'`,
    CALENDAR: `CALNUM = '${params}'`,
    CLASSSTRUCTURE: `CLASSSTRUCTUREID =  '${params}'`,
    COMMTEMPLATE: `TEMPLATEID = '${params}'`,
    CONDITION: `CONDITIONNUM = '${params}'`,
    CRONTASKDEF: `CRONTASKNAME = '${params}'`,
    CTRLGROUP: `APP = '${params}'`,
    MAXDOMAIN: `DOMAINID = '${params}'`,
    ESCALATION: `ESCALATION = '${params}'`,
    VST_GLOBMULTIVAL: `VST_GMVNAME = '${params}'`,
    LaunchPoints: `LAUNCHPOINTNAME = '${params}' `,
    MAXENDPOINT: `ENDPOINTNAME = '${params}'`,
    MAXGROUP: `GROUPNAME = '${params}'`,
    MAXIFACECONTROL: `IFACECONTROL = '${params}'`,
    MAXLOGAPPENDER: `APPENDER = '${params}'`,
    MAXLOGGER: `LOGKEY = '${params}'`,
    // MAXMESSAGES: `MSGGROUP = 'CP_LOCVALIDATE' AND MSGKEY = 'CP_PART3ERROR'`,
    MAXSERVICE: `SERVICENAME = '${params}'`,
    MEASUREUNIT: `MEASUREUNITID = '${params}'`,
    MAXOBJECTCFG: `OBJECTNAME = '${params}'`,
    MAXINTOBJECT: `INTOBJECTNAME = '${params}'`,
    PERSON: `PERSONID = '${params}'`,
    PERSONGROUP: `PERSONGROUP = '${params}'`,
    // QUERY: `app = 'PLUSWOTR' and clausename = 'CP_ PEGHOLD' AND owner  = 'MAXADMIN'`,
    MAXRELATIONSHIP: `PARENT = '' AND NAME = '${params}'`,
    REPORT: `APPNAME = ' ' AND REPORTNAME = '${params}'`,
    REPORTDESIGN: `REPORTNAME = '${params}'`,
    MAXROLE: `MAXROLE = '${params}'`,
    MAXAPPS: `APP = '${params}'`,
    Screen: `APP = '${params}'`,
    SCTEMPLATE: `NAME = '${params}'`,
    // SECURITYRESTRICT: `OBJECTNAME = 'WORKORDER' AND ATTRIBUTENAME = 'DESCRIPTION' AND APP = 'PLUSCMT' AND CONDITIONNUM = 'CP_CMT_REGAF'`,
    SHIFT: `SHIFTNUM = '${params}'`,
    SIGOPTION: `APP = '${params}'`,
    MAXPRESENTATION: `APP = '${params}'`,
    WFPROCESS: `PROCESSNAME = '${params}'`,
  };

  return dataTemplate;
};
